/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117673-gbb57b78013-20241028"
#endif /* AVUTIL_FFVERSION_H */
